import type { Metadata } from 'next'
import { IBM } from './fonts/font'
import './globals.css'


export const metadata: Metadata = {
  title: 'Portfolio Alicia Lo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={IBM.variable}>{children}</body>
    </html>
  )
}
